version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306" # For MySQL Server
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app/backend # Mount your local backend folder to /app inside container.
      # - /app/node_modules # Important: Prevent overwriting node_modules inside container
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: mydatabase
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports: 
      - "3000:3000" # For Node Express Server
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

volumes:
  mysql-data:
